### ISSUE TITLE
Drobo 5N2 - NFSv3 - Unable to load kernal modules

### ISSUE THREAD

**Issue by black-nest** [droboports/nfs#10]
I am running the below versions:
Drobo 5N2 - 4.0.0 [13.13.89501]
Drobo Dashboard - 3.0.0 [88901]

When I install the NFSv3 app I get an error stating that it was "Unable to load kernal modules, please see log.txt for more information"

I understand from other posts that the kernal modules are no longer downloaded with the app but should be downloaded with the dashboard software. How do I resolve this issue?

Thanks!

**Comment by ricardopadilha** [comment]
Drobo pushed the kernel modules for the 5N2 to their FTP servers. Please try again, it should work now.
