### ISSUE TITLE
NFS4.2

### ISSUE THREAD

**Issue by nwhistler** [droboports/nfs#12]
Hi,

Any chance of getting an upgrade for NFS4.2?

I was just reading up on it and it has some pretty killer features:
http://www.datacenterknowledge.com/industry-perspectives/seven-new-nfs-capabilities

**Comment by ricardopadilha** [comment]
Sorry, but that would require a kernel compiled with support for NFS v4.2. Currently the Drobo devices only support up to NFS v3.

**Comment by nwhistler** [comment]
Ok, thanks.
