### ISSUE TITLE
Can't find lsmod or insmod

### ISSUE THREAD

**Issue by mpbono** [droboports/nfs#4]
I just downloaded and installed the latest version of nfs for the Drobo B800fs.  When I try to start the service, the log file shows the following:

$ ./service.sh start
$ cat /tmp/DroboApps/nfs/log.txt

2015-08-31 00-11-17: ./service.sh start
- _service_start
- _is_running
- _is_name_running nfsd
- killall -0 nfsd
- return 1
- set +x
- local force_restart=0
- [[ ! -f /etc/services ]]
- chmod 4511 /mnt/DroboFS/Shares/DroboApps/nfs/sbin/mount.nfs
- chown -R nobody /mnt/DroboFS/Shares/DroboApps/nfs/var/lib/nfs/sm /mnt/DroboFS/Shares/DroboApps/nfs/var/lib/nfs/sm.bak /mnt/DroboFS/Shares/DroboApps/nfs/var/lib/nfs/state
- _load_modules
- uname -r
- local kversion=2.6.22.18
- local modules=exportfs nfsd
- lsmod
  ./service.sh: line 1: lsmod: not found
- grep ^exportfs
- [[ -z  ]]
- insmod /mnt/DroboFS/Shares/DroboApps/nfs/modules/2.6.22.18/exportfs.ko
  ./service.sh: line 1: insmod: not found

Any idea what I have messed up?  I have a little knowledge of Linux/UNIX, but am not an expert.

nfs/etc/netconfig:
udp        tpi_clts      v     inet     udp     -       -
tcp        tpi_cots_ord  v     inet     tcp     -       -
udp6       tpi_clts      v     inet6    udp     -       -
tcp6       tpi_cots_ord  v     inet6    tcp     -       -
rawip      tpi_raw       -     inet      -      -       -
local      tpi_cots_ord  -     loopback  -      -       -
unix       tpi_cots_ord  -     loopback  -      -       -

nfs/etc/exports:
$ cat exports
/mnt/DroboFS/Shares/VMwareNFS 192.168.1.99(rw,insecure,no_subtree_check,all_squash,anonuid=0,anongid=0)
/mnt/DroboFS/Shares/Public    0.0.0.0/0(rw,insecure,no_subtree_check,all_squash,anonuid=99,anongid=99)
/mnt/DroboFS/Shares/Music     0.0.0.0/0(rw,insecure,no_subtree_check,all_squash,anonuid=99,anongid=99)
/mnt/DroboFS/Shares/PcBackups 0.0.0.0/0(rw,insecure,no_subtree_check,all_squash,anonuid=99,anongid=99)
/mnt/DroboFS/Shares/Photos    0.0.0.0/0(rw,insecure,no_subtree_check,all_squash,anonuid=99,anongid=99)
/mnt/DroboFS/Shares/Video     0.0.0.0/0(rw,insecure,no_subtree_check,all_squash,anonuid=99,anongid=99)

**Comment by ricardopadilha** [comment]
It looks like the $PATH variable is not being properly setup. When you type `echo $PATH`, what do you get back?

Also, are you starting the app as root? A normal user cannot start apps.

**Comment by mpbono** [comment]
Thanks for the quick response!

Umm...  I was logged in as Admin, not root.

When I log in as root:

# echo $PATH

/usr/bin:/bin

# ./service.sh start

# ./service.sh status

nfs is enabled and stopped

# ps

  PID USER       VSZ STAT COMMAND
    1 root      3032 S    init
    2 root         0 SW<  [kthreadd]
    3 root         0 SWN  [ksoftirqd/0]
    4 root         0 SW<  [watchdog/0]
    5 root         0 SW<  [events/0]
    6 root         0 SW<  [khelper]
   29 root         0 SW<  [kblockd/0]
   44 root         0 SW   [pdflush]
   45 root         0 SW   [pdflush]
   46 root         0 SW<  [kswapd0]
   47 root         0 SW<  [aio/0]
   48 root         0 SW   [crypto]
   49 root         0 SW   [crypto_ret]
  183 root         0 SW<  [dri_dnas_thread]
  186 root         0 SW<  [mtdblockd]
  187 root         0 SW<  [nftld]
  198 root         0 SWN  [jffs2_gcd_mtd1]
  206 root         0 SWN  [jffs2_gcd_mtd2]
  224 root      1584 S    /sbin/netplugd -P
  228 root      3036 S    /bin/sh /usr/bin/nasdLogRotate
  230 root     11276 S    /usr/bin/nasd-fugi
  231 root      3036 S    -/bin/sh
  253 root      3032 S    udhcpc -i eth1 -s /etc/udhcpc.sh -b
  270 root         0 SW<  [dri_shared_res_]
  271 root         0 SW<  [dri_scsi_resp_2]
  272 root         0 SW<  [dri_scsi_req_3]
  275 root         0 SW<  [scsi_eh_0]
  310 root         0 SW<  [kjournald]
  315 root         0 SW<  [kjournald]
  392 root      5544 S    /sbin/nmbd -s
/mnt/DroboFS/System/samba/conf/smb.conf
  394 root     10068 S    /sbin/smbd -s
/mnt/DroboFS/System/samba/conf/smb.conf
  395 root     10068 S    /sbin/smbd -s
/mnt/DroboFS/System/samba/conf/smb.conf
  409 avahi     2688 S    avahi-daemon: running [Drobo1.local]
  412 root      2960 S    /sbin/cnid_metad
  415 root      6264 S    /sbin/afpd -F
/mnt/DroboFS/System/netatalk/conf/afpd.conf -P
/mnt/DroboFS/System/netatalk/security/afpd.pid
  450 root      2020 S    /sbin/dropbear -E -P
/tmp/DroboApps/dropbear/pid.txt -r
/mnt/DroboFS/Shares/DroboApps/dropbear/dropbear.key
 1148 root      3032 S    /bin/sh /etc/init.d/restart_nasd
 7825 root     10340 S    /sbin/smbd -s
/mnt/DroboFS/System/samba/conf/smb.conf
 7878 root      2500 R    /sbin/dropbear -E -P
/tmp/DroboApps/dropbear/pid.txt -r
/mnt/DroboFS/Shares/DroboApps/dropbear/dropbear.key
 7879 root      3036 S    -sh
 8477 root      2900 S    sleep 30
 8479 root      2900 S    sleep 30
 8480 root      3036 R    ps

# cat /mnt/DroboNAS/Shares/DroboApps/nfs/log.txt

#

**Comment by ricardopadilha** [comment]
This is the $PATH you should have:

```
# echo $PATH
/sbin:/usr/sbin:/bin:/usr/bin
```

Try to `export PATH=/sbin:/usr/sbin:/bin:/usr/bin`, and see if that helps.

In any case, there seems to be something wrong with your setup. PATH for root should include /sbin and /usr/sbin. Are you using `sudo`, by any chance?

**Comment by mpbono** [comment]
Nope, I was using sudo when I was logged in as Admin, but I did not use it
when root.

This evening, I will uninstall nfs, reboot the Drobo, drop in nfs, reboot
Drobo, and see if that helps.

Thanks!
==mpb

**Comment by mpbono** [comment]
I Reinstalled nfs, but on restart, the $PATH was wrong again.  I exported
$PATH with your suggestion, and I am able to start NFS and access the share
from VMware! -- Huge success!

I want to create a start up script that will set the $PATH.  I am used to
putting a script in /etc/init.d/ but the DroboFS directory tree is
different.  Can you tell me where to put a script so that it gets executed
when the DroboFS boots?  Or should I just add it to "service.sh" file in
the nfs directory?

Thanks for all of your help!  This is a great addition to the Drobo!
==mpb

**Comment by ricardopadilha** [comment]
The change in commit 93461e2 should fix this for you without messing with system files.
