### ISSUE TITLE
NFS modules won't load into Drobo 5N with firmware 3.5.10 

### ISSUE THREAD

**Issue by TomKeddie** [droboports/nfs#7]
I'm unable to load the nfs kernel modules into recent firmware.  I emailed requesting updated kernel source back in March and was told to wait.  Have emailed again since with no response.

> Drobo5N:~/Shares/Media/tmp/modules/3.2.58-3.5.0 # uname -a
> Linux Drobo5N 3.2.58-2 #1 SMP Fri Apr 1 12:41:27 PDT 2016 armv7l GNU/Linux
> 
> Drobo5N:~/Shares/Media/tmp/modules/3.2.58-3.5.0 # insmod nfsd.ko 
> insmod: can't insert 'nfsd.ko': invalid module format
> 
> Drobo5N:~/Shares/Media/tmp/modules/3.2.58-3.5.0 # dmesg | tail -1
> [ 1686.052471] nfsd: version magic '3.2.58 SMP mod_unload ARMv7 ' should be '3.2.58-2 SMP mod_unload ARMv7 '

**Comment by ricardopadilha** [comment]
This is strange, because I'm running the NFS app on 3.5.10 without any troubles:

```
# uname -a
Linux Drobo64 3.2.58-2 #1 SMP Fri Apr 1 12:41:27 PDT 2016 armv7l GNU/Linux
# lsmod
nfsd 87543 6 - Live 0x7f000000
```

Which version of the app are you running? Did you update to the latest available from Drobo Dashboard?

**Comment by TomKeddie** [comment]
> Which version of the app are you running?

I just tried again with "NFSv3 1.3.2-2" from https://github.com/droboports/nfs/releases, fails.

Drobo5N:~/Shares/Media/tmp/nfs # md5sum modules/3.2.58-3.5.0/nfsd.ko 
dbcf17faabc444e08eb06cfc573b0e98  modules/3.2.58-3.5.0/nfsd.ko

Drobo5N:~/Shares/Media/tmp/nfs # strings modules/3.2.58-3.5.0/nfsd.ko | grep mod
_unload
vermagic=3.2.58 SMP mod_unload ARMv7 

> Did you update to the latest available from Drobo Dashboard?

Latest Drobo firmware and Dashboard, yes.

![image](https://cloud.githubusercontent.com/assets/4367175/15052268/97f4f72a-12b1-11e6-838c-8cd65f54899d.png)

**Comment by ricardopadilha** [comment]
> Latest Drobo firmware and Dashboard, yes.

Sorry, I meant the latest NFS DroboApp, installed from Drobo Dashboard. As you can see from the commit log [1](https://github.com/droboports/nfs/compare/v1.3.2-2...master) the kernel modules are no longer shipped with the app, they are downloaded from the official DroboApp repository.

I came to this arrangement with Drobo so that the NFS DroboApp will no longer need to be updated every time there is a new firmware out. The app will automatically reach out to the official DroboApp repository and download the latest kernel modules.

**Comment by TomKeddie** [comment]
> I came to this arrangement with Drobo so that the NFS DroboApp will no longer need to be updated every time there is a new firmware out. The app will automatically reach out to the official DroboApp repository and download the latest kernel modules.

Thanks,  I can see it now but i need to work out how to clean my other attempts to install first.  Closing, thanks for your help.
