### ISSUE TITLE
Not Compatible With Firmware 3.5.10

### ISSUE THREAD

**Issue by thewunder** [droboports/nfs#8]
The kernel module doesn't load...

**Comment by ricardopadilha** [comment]
Are you using the latest version from Drobo Dashboard?

**Comment by thewunder** [comment]
I just downloaded the release from github...

**Comment by ricardopadilha** [comment]
Yeah, you should be using the latest one from Drobo Dashboard. Give that a try, it should work.

**Comment by thewunder** [comment]
Thanks!
